production:
   auto_create: true
   deny_delete: true
   allow_add_local: true
   post_create: %INSTALL_DIR%/bin/scm-post-create
   svn:
     path: /var/opt/redmine/svn
     svnadmin: /usr/bin/svnadmin
     url: repos/svn
   git:
     path: /var/opt/redmine/git
     git: /usr/bin/git
     options: --bare
     url: repos/git
